### ISSUE TITLE
Windows Package Cannot find module 'electron'

### ISSUE THREAD

**Issue by tylerbourque** [maxogden/electron-packager#248]
After building a package for windows via:
`electron-packager ./ <appName> --platform=win32 --arch=x64 --version=0.33.7` 

When I try to run the exe located inside the build folder I get an error  saying cannot find module 'electron'

![image](https://cloud.githubusercontent.com/assets/8410111/12638661/0fac82b6-c56d-11e5-80b7-fe253b875e23.png)

my folder structure looks like this if it makes a difference... 

![image](https://cloud.githubusercontent.com/assets/8410111/12638679/22deaabc-c56d-11e5-907a-d6e35942c4df.png)

and my main process code looks like
https://gist.github.com/tylerbourque/54714e5c5120583d1d0f

**Comment by kfranqueiro** [comment]
Your code looks like it was written against Electron [0.35+](https://github.com/atom/electron/releases/tag/v0.35.0) (which is what added the centralized `electron` module), but you're telling electron-packager to build using 0.33.

**Comment by tylerbourque** [comment]
ok so i switched so build with version 0.35.0 

`electron-packager ./ <appName> --platform=win32 --arch=x64 --version=0.35.0`

now there is an error saying `unable to find valid app`

**Comment by malept** [comment]
Per the issue reporting guidelines in [CONTRIBUTING.md](https://github.com/maxogden/electron-packager/blob/master/CONTRIBUTING.md):
> * Which version of electron-packager are you using?
> * What platform are you running electron-packager on?

**Comment by tylerbourque** [comment]
electron-packager version is: 5.2.1
and i am running on a 64bit Windows 10 machine.

here is the new error:
![image](https://cloud.githubusercontent.com/assets/8410111/12650783/221de9c2-c5b2-11e5-858a-036dcadac74f.png)

**Comment by malept** [comment]
What does the folder structure of `D:\Projects\ElectronApps\testApp\electron-quick-start\testApp-win32-x64` look like?

**Comment by tylerbourque** [comment]
Root of that folder is: 
![image](https://cloud.githubusercontent.com/assets/8410111/12651166/77f0bc0c-c5b3-11e5-84e7-bf04be5b0381.png)

and inside the resources folder it contains:

-app
--- inside here looks like the root of the project itself 
-atom.asar

**Comment by malept** [comment]
I'm more interested in `resources\app`. Does it look like the source dir?

**Comment by tylerbourque** [comment]
yes it looks like a mirror image of the source dir

**Comment by malept** [comment]
Hmmm. Try building with either the git master version of electron-packager or an older version. Perhaps that will fix the error?

**Comment by tylerbourque** [comment]
Ok found the issue.

So i tried to build with 5.2.0 and it worked but when i ran the app it opened the default app a believe. The "Welcome to Electron to run your app..." so I then just tried to start it with npm start. Apparently I had a trailing comma. once i fixed this it builds fine with both 5.2.1 and 5.2.0

**Comment by nikhiljha** [comment]
I have the same problem, but when I run the app I actually have the app that I wanted to make.

I'm running
`electron-packager . WhatsApp --platform=win32 --arch=x64 --version=0.36.10 --out=C:\Users\nikhil\WAD-Bins --overwrite`

and I get the same folder structure as tylerbourque.

**Comment by nikhiljha** [comment]
The trailing comma is generated by npm init - which is kind of weird. The 'trailing comma' also passes the JS yaml parser - so this shouldn't be happening.

**Comment by Deepakchawla** [comment]
Run this command 

npm install --save-dev electron[https://www.christianengvall.se/electron-packager-tutorial/](url)

**Comment by lysShub** [comment]
maybe you install electron global, in your project:
`c
E:\OneDrive\code\electron\mydemo>electron-packager .
Cannot find module 'electron' from 'E:\OneDrive\code\electron\mydemo'

E:\OneDrive\code\electron\mydemo>npm install --save-dev electron
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
......

E:\OneDrive\code\electron\mydemo>electron-packager .
Downloading electron-v1.8.8-win32-x64.zip: [========================================-----------] 78% ETA: 58.2 seconds 
.......
`
